/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    programmes: Programme;
    events: Event;
    coaches: Coach;
    testimonials: Testimonial;
    faqs: Faq;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('super-admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the root /  page.
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  layout?:
    | (
        | {
            badge?: string | null;
            heading: string;
            /**
             * This exact text within the heading will be styled in gold.
             */
            headingHighlight?: string | null;
            subheading?: string | null;
            primaryButtonLabel?: string | null;
            primaryButtonLink?: string | null;
            secondaryButtonLabel?: string | null;
            secondaryButtonLink?: string | null;
            backgroundImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            stats?:
              | {
                  number: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subheading?: string | null;
            features?:
              | {
                  icon?: ('shield' | 'trophy' | 'users' | 'star' | 'heart' | 'target' | 'award' | 'check') | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Select up to 3–4 programmes to highlight. Leave empty to show the first 3 active programmes.
             */
            programmes?: (number | Programme)[] | null;
            viewAllLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programmes-preview';
          }
        | {
            imagePosition?: ('left' | 'right') | null;
            image: number | Media;
            badgeText?: string | null;
            /**
             * Gold badge overlaid on the image corner (e.g. "8+ Years of Excellence").
             */
            overlayBadge?: {
              number?: string | null;
              label?: string | null;
            };
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttonLabel?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-content';
          }
        | {
            /**
             * Select the event to promote in this banner.
             */
            event?: (number | null) | Event;
            /**
             * A dark overlay is applied automatically.
             */
            backgroundImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'event-banner';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Leave empty to auto-show all featured testimonials (in display order).
             */
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Displayed above the heading.
             */
            image?: (number | null) | Media;
            heading: string;
            subheading?: string | null;
            variant?: ('white' | 'green' | 'light-green') | null;
            buttons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('primary' | 'gold' | 'outline' | 'phone') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('prose' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
      )[]
    | null;
  meta?: {
    /**
     * Defaults to the page title + site name.
     */
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage coaching programmes shown on the Programmes page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Used in URLs.
   */
  slug: string;
  status?: ('active' | 'coming-soon' | 'archived') | null;
  ageRange: string;
  level: string;
  price: string;
  sessionDuration?: string | null;
  frequency?: string | null;
  location?: string | null;
  description: string;
  /**
   * Bullet-point list shown on the programme card.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  prerequisites?: string | null;
  /**
   * Colour stripe at the top of the programme card.
   */
  accentColor?: ('green' | 'gold' | 'emerald' | 'purple') | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage events and camps shown on the Events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  slug: string;
  status?: ('upcoming' | 'past' | 'cancelled' | 'draft') | null;
  /**
   * Highlighted with a gold banner on the Events page.
   */
  featured?: boolean | null;
  date: string;
  time?: string | null;
  registrationDeadline?: string | null;
  location?: string | null;
  ageRange?: string | null;
  level?: string | null;
  price?: string | null;
  description: string;
  /**
   * Bullet points shown under "What to Expect" heading.
   */
  expectations?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Parent testimonials shown on the Home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  parentName: string;
  childDescription: string;
  /**
   * If not provided, initials will be shown instead.
   */
  photo?: (number | null) | Media;
  /**
   * Write in first person. Do not include quotation marks — they are added automatically.
   */
  quote: string;
  rating?: ('5' | '4' | '3') | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage coach profiles shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  name: string;
  /**
   * e.g. Head Coach & Founder
   */
  title: string;
  /**
   * Square headshot recommended. Displayed on the About page.
   */
  photo?: (number | null) | Media;
  bio: string;
  /**
   * Shown as badges on the coach card.
   */
  certifications?:
    | {
        certification: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first. Head coach should be 1.
   */
  order?: number | null;
  /**
   * Marks this coach as the designated Safeguarding Lead.
   */
  isSafeguardingLead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage FAQ entries shown on the FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  category: 'getting-started' | 'practical' | 'safety' | 'costs' | 'other';
  question: string;
  answer: string;
  /**
   * Lower numbers appear first within the same category.
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries submitted through the Contact page form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  parentName: string;
  email: string;
  phone?: string | null;
  childName: string;
  childAge: number;
  programme?: ('trial' | 'little-legends' | 'rising-stars' | 'elite' | 'private' | 'camp') | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  /**
   * Internal notes — not visible to the enquirer.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              heading?: T;
              headingHighlight?: T;
              subheading?: T;
              primaryButtonLabel?: T;
              primaryButtonLink?: T;
              secondaryButtonLabel?: T;
              secondaryButtonLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'programmes-preview'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              programmes?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        'image-content'?:
          | T
          | {
              imagePosition?: T;
              image?: T;
              badgeText?: T;
              overlayBadge?:
                | T
                | {
                    number?: T;
                    label?: T;
                  };
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'event-banner'?:
          | T
          | {
              event?: T;
              backgroundImage?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              image?: T;
              heading?: T;
              subheading?: T;
              variant?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  ageRange?: T;
  level?: T;
  price?: T;
  sessionDuration?: T;
  frequency?: T;
  location?: T;
  description?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  prerequisites?: T;
  accentColor?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  time?: T;
  registrationDeadline?: T;
  location?: T;
  ageRange?: T;
  level?: T;
  price?: T;
  description?: T;
  expectations?:
    | T
    | {
        item?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  certifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  order?: T;
  isSafeguardingLead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  parentName?: T;
  childDescription?: T;
  photo?: T;
  quote?: T;
  rating?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  category?: T;
  question?: T;
  answer?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  parentName?: T;
  email?: T;
  phone?: T;
  childName?: T;
  childAge?: T;
  programme?: T;
  message?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global settings — contact details, SEO defaults, social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Used in the navigation bar and footer.
   */
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  safeguardingEmail?: string | null;
  address?: string | null;
  officeHours?: string | null;
  instagramUrl?: string | null;
  facebookUrl?: string | null;
  youtubeUrl?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  footerAboutText?: string | null;
  footerCopyright?: string | null;
  newsletterHeading?: string | null;
  newsletterSubtext?: string | null;
  announcementEnabled?: boolean | null;
  announcementText?: string | null;
  announcementLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header navigation links and CTA button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  phone?: T;
  email?: T;
  safeguardingEmail?: T;
  address?: T;
  officeHours?: T;
  instagramUrl?: T;
  facebookUrl?: T;
  youtubeUrl?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  footerAboutText?: T;
  footerCopyright?: T;
  newsletterHeading?: T;
  newsletterSubtext?: T;
  announcementEnabled?: T;
  announcementText?: T;
  announcementLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}